#!/bin/bash

# installing some Programms
sudo pacman -Syu
sudo pacman -S xorg xorg-server xterm xfce4-terminal lightdm-gtk-greeter lightdm fluxbox archlinux-wallpaper vlc nano firefox pavucontrol feh

fluxbox-generate_menu

#Testing Lightdm
sudo systemctl enable lightdm
sudo systemctl start lightdm


cp /etc/xdg/xfce4/xinitrc /etc/X11/xinit/xinitrc    
