#!/bin/bash

sudo pacman -Syu

echo "Vil du installere Gnome Desktop? (j/n)"
red svar

if [ $svar == 'j' ]
then
sudo pacman -S xorg xorg-server gnome firefox vlc gnome-tweaks nano
else
fi

#vil du test GDM
echo "Vil du starte GDM? (j/n)"
read var
if [ $var == 'j' ]
then
  sudo systemctl start gdm
else

fi
