#!/bin/bash

sudo pacman -Syu

echo "Install Gnome Desktop? (y/n)"
read svar

if [ $svar == 'y' ]
then
sudo pacman -S xorg xorg-server gnome gnome-extra vivaldi vlc gnome-tweaks nano
sudo systemctl enable gdm
else
#vil du test GDM
echo "Would you start GDM? (y/n)"
read var

sudo systemctl enable gdm

if [ $var == 'y' ]
then
  sudo systemctl start gdm

fi
fi
    
