#!/bin/bash

sudo pacman -Syu

echo "Vil du installere Gnome Desktop? (j/n)"
read svar

if [ $svar == 'j' ]
then
sudo pacman -S xorg xorg-server gnome gnome-extra vivaldi vlc gnome-tweaks nano
else
#vil du test GDM
echo "Vil du starte GDM? (j/n)"
read var
if [ $var == 'j' ]
then
  sudo systemctl start gdm

fi
fi
    
