#!/bin/bash

# installing some Programms.
sudo pacman -Syu
sudo pacman -S xorg xorg-server xterm lightdm-gtk-greeter lightdm lxqt breeze-icons mpv nano firefox pavucontrol

#Testing Lightdm

sudo systemctl enable lightdm
sudo systemctl start lightdm

cp /etc/xdg/lxqt/xinitrc /etc/X11/xinit/xinitrc 
