#!/bin/bash

# installing some Programms.
sudo pacman -Syu
sudo pacman -S xorg xorg-server xterm lightdm-gtk-greeter lightdm openbox obconf menumaker  vlc nano flatpak firefox pavucontrol feh

#Testing Lightdm

sudo systemctl enable lightdm
sudo systemctl start lightdm

mkdir -p /home/arch/.config/openbox
cp -a /etc/xdg/openbox /home/arch/.config

flatpak install flathub com.valvesoftware.Steam
    
mmaker -vf openbox3
