#!/bin/bash

sudo pacman -Syu

echo "Vil du installere xfce Desktop? (j/n)"
read svar

if [ $svar == 'j' ]
then
sudo pacman -S xorg xorg-server xterm lightdm xfce4 xfce4-goodies vlc nano firefox
else
#vil du test GDM
echo "Vil du starte lightdm? (j/n)"
read var
if [ $var == 'j' ]
then
  sudo systemctl start lightdm

fi
fi
    
