#!/bin/bash

# installing some Programms.
sudo pacman -Syu
sudo pacman -S xorg xorg-server xterm lightdm-gtk-greeter lightdm xfce4 xfce4-goodies vlc nano firefox pavucontrol

#Testing Lightdm

sudo systemctl enable lightdm
sudo systemctl start lightdm

cp /etc/xdg/xfce4/xinitrc /etc/X11/xinit/xinitrc    
